name: marslab
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - pandas
  - matplotlib
  - git
  - pip
  - python-Levenshtein
  - scipy
  - fs
  - pathos
  - cytoolz
  - dustgoggles
  - python-dateutil
  - pdr
  - astropy
  - sympy
  - more-itertools
  - fast-histogram
  - scikit-image
  - opencv
