name: marslab
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy
  - pandas
  - matplotlib
  - git
  - jupyter
  - clize
  - pip
  - gdal
  - rasterio
  - pvl
  - python-Levenshtein
  - scipy
  - scikit-image
  - opencv
  - fs
  - pathos
  - cytoolz
  - python-dateutil
  - pip:
      - git+https://github.com/MillionConcepts/pdr.git
      - git+https://github.com/MillionConcepts/dustgoggles.git
  - astropy
  - sympy
  - more-itertools
  - pytest
  - pytest-cov
  - hypothesis
